allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@portabletext/editor@7.10.11'
  - '@portabletext/plugin-character-pair-decorator@8.0.39'
  - '@portabletext/plugin-dnd@1.0.23'
  - '@portabletext/plugin-input-rule@6.0.8'
  - '@portabletext/plugin-list-index@1.0.23'
  - '@portabletext/plugin-markdown-shortcuts@8.0.39'
  - '@portabletext/plugin-one-line@7.0.38'
  - '@portabletext/plugin-paste-link@4.0.38'
  - '@portabletext/plugin-table@1.3.8'
  - '@portabletext/plugin-typography@8.0.39'
  - '@sanity/cli@7.12.1'
  - '@sanity/diff@6.6.0'
  - '@sanity/mutator@6.6.0'
  - '@sanity/schema@6.6.0'
  - '@sanity/types@6.6.0'
  - '@sanity/util@6.6.0'
  - '@sanity/vision@6.6.0'
  - '@sanity/workbench-cli@1.7.1'
  - '@sanity/workbench@0.1.0-alpha.29'
  - sanity@6.6.0
  - '@sanity/astro@3.5.0'
onlyBuiltDependencies:
  - esbuild
  - sharp
